module.exports.Reward_Contract = {
  address: "0x3D5C50F93c6b307De88b4C63212cca746673278F",
  // address: '0x9837460bb7ac19dd72e8c3267084207ced1e95a9',
  ABI: [
    {
      inputs: [{ internalType: "address", name: "_token", type: "address" }],
      payable: false,
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      constant: false,
      inputs: [
        { internalType: "address", name: "vault", type: "address" },
        { internalType: "uint256", name: "amount", type: "uint256" },
      ],
      name: "claim",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ internalType: "address", name: "vault", type: "address" }],
      name: "claimAll",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "governance",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: true,
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "address", name: "", type: "address" },
      ],
      name: "rewardData",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { internalType: "address", name: "_governance", type: "address" },
      ],
      name: "setGovernance",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [
        { internalType: "address", name: "vault", type: "address" },
        { internalType: "address[]", name: "_addressList", type: "address[]" },
        { internalType: "uint256[]", name: "_reward", type: "uint256[]" },
      ],
      name: "setReceiver",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: false,
      inputs: [{ internalType: "address", name: "_token", type: "address" }],
      name: "setToken",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      constant: true,
      inputs: [],
      name: "token",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      payable: false,
      stateMutability: "view",
      type: "function",
    },
  ],
};
